### ISSUE TITLE
Output not working

### ISSUE THREAD

**Issue by ghost** [XenocodeRCE/Noisette-Obfuscator#6] opened 2016-08-25 19:36 UTC
the title explains everything... here is a link of the file im obfuscating.

http://www67.zippyshare.com/v/eWFAF11j/file.html

**Comment by XenocodeRCE** [comment] 2016-08-25 19:38
Nice, now happy debugging, update the issue one you find the cause :)

**Comment by ghost** [comment] 2016-08-25 19:42
startup form has not been specified are u kidding me? VS got cancer or sth?

**Comment by XenocodeRCE** [comment] 2016-09-19 09:00
No reply since 25 days, I close this.

**Closed as completed by XenocodeRCE** 2016-09-19 09:00 UTC
